### PR TITLE
when hostname equal "", openssl should not check sni

### PR DESCRIPTION
**Pull request by jm-observer**

### CODE REVIEW

**Comment by fafhrd91** [comment]
this is wrong approach. this pr silently reduces security of the connection.

**Comment by jm-observer** [comment]
hi, fafhrd91. please see my [examples ](https://github.com/jm-observer/ntex-example/tree/main/examples)about this pr. In my examples, i try to connet same mqtt broker by three ways, but the result is different.The connection will only succeed if the uri is used, other will be fail because &str parsing hostname error, or the socketaddress simply does not have hostname.do you think the result is right?

**Comment by fafhrd91** [comment]
it doesnt matter. silently reducing security is just not acceptable.

**Comment by fafhrd91** [comment]
you can remove sni check for your own setup.

**Comment by jm-observer** [comment]
um, you are right. so can you give me a example to remove sni check, from what I know now, I can't? Should an additional configuration parameter be provided to allow the user to control the operation?

> it doesnt matter. silently reducing security is just not acceptable.

**Comment by fafhrd91** [comment]
it is fixed in master. update ntex-connect to 0.1.1

**Pull request closed without merging**
