### PR TITLE
Allow passing Tokio Handle on ntex-rt

### PR DESCRIPTION
**Pull request by pavlospt**

### CODE REVIEW

**Comment by fafhrd91** [comment]
idea is right, but I would make "handle: Option<Handle>", and added ".new_with_handle(..)" methods.

**Comment by fafhrd91** [comment]
as I remember you can use Handle::new() instead of actual handle.

**Comment by fafhrd91** [comment]
https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html#method.current

**Comment by pavlospt** [comment]
> https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html#method.current

Indeed `::current()` is what I use in tests. Maybe you mean something else?

**Comment by fafhrd91** [comment]
use current(), and something like use_current_handle: bool in builder

**Comment by pavlospt** [comment]
I have some tests that take longer than 60s on Ntex-rt and they fail with timeout. I believe I have reached the peak of my understanding of how the underlying system works here 😛 If you have more hints or advice let me know :D

**Comment by fafhrd91** [comment]
add env_logger::init() to your test and try to run it with RUST_LOG=trace

**Comment by pavlospt** [comment]
I have tried that and also tried debugging it. It seems that the other test is panicking because it cannot find a configured runtime and panics at: `lib.rs#353`. I am not sure how to enable `tokio` feature for this test and I am out of ideas :/

**Comment by fafhrd91** [comment]
default behavior must be same as before, running with handler must be enabled explicitly

**Comment by pavlospt** [comment]
But if this is not enabled with a Cargo feature then how am I going to import `Handle` 🤔 ?

**Comment by pavlospt** [comment]
`Handle` though resides in `tokio` crate. So if `tokio` feature is not enabled then how will the library compile when it needs to
```rust
use tok_io::runtime::Handle;
```
🤔

**Comment by fafhrd91** [comment]
mark import with feature or move it inside block that already marked with feature

**Comment by pavlospt** [comment]
Ok I am now thinking this issue is above my skills with the language 😛 Thank for your time and your explanations though 🙏🏻

**Comment by fafhrd91** [comment]
I will take check what I can do next weekend

**Comment by fafhrd91** [comment]
here is example how to use tokio https://github.com/ntex-rs/examples/blob/1a365350df3a9c904da5fbaa3b1e479fdb9191da/tokio/src/main.rs#L77

**Pull request closed without merging**
