### PR TITLE
add some tests for BytesVec

### PR DESCRIPTION
**Pull request by goiw111**

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you add entry to changes, and will make new release

**Comment by goiw111** [comment]
this is my first ever pull requests., ok i will do

**Comment by goiw111** [comment]
is that ok ?

**Comment by fafhrd91** [comment]
it us good. lets just wait for tests pass and then i will merge

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
thanks!

**Pull request merged**
