### PR TITLE
Refresh GitHub workflows

### PR DESCRIPTION
**Pull request by pavlospt**
_Per title_

### CODE REVIEW

**Review by fafhrd91 — APPROVED** [review]
lgtm

**Comment by fafhrd91** [comment]
thanks!

**Comment by fafhrd91** [comment]
thanks!

**Comment by pavlospt** [comment]
@fafhrd91 do you want me to fix the rest of the Clippy warnings as well?

**Comment by fafhrd91** [comment]
I will take care of Glommio warnings

**Pull request merged**
